//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.06 at 02:12:50 PM IST 
//


package com.jp.cleartrip.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.cleartrip.com/air/}solutions"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}onward-solutions"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}return-solutions"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}ancillary-data"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "solutionsOrOnwardSolutionsOrReturnSolutions"
})
@XmlRootElement(name = "air-search-result")
public class AirSearchResult {

    @XmlElements({
        @XmlElement(name = "onward-solutions", type = OnwardSolutions.class),
        @XmlElement(name = "solutions", type = Solutions.class),
        @XmlElement(name = "ancillary-data", type = AncillaryData.class),
        @XmlElement(name = "return-solutions", type = ReturnSolutions.class)
    })
    protected List<Object> solutionsOrOnwardSolutionsOrReturnSolutions;

    /**
     * Gets the value of the solutionsOrOnwardSolutionsOrReturnSolutions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the solutionsOrOnwardSolutionsOrReturnSolutions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSolutionsOrOnwardSolutionsOrReturnSolutions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnwardSolutions }
     * {@link Solutions }
     * {@link AncillaryData }
     * {@link ReturnSolutions }
     * 
     * 
     */
    public List<Object> getSolutionsOrOnwardSolutionsOrReturnSolutions() {
        if (solutionsOrOnwardSolutionsOrReturnSolutions == null) {
            solutionsOrOnwardSolutionsOrReturnSolutions = new ArrayList<Object>();
        }
        return this.solutionsOrOnwardSolutionsOrReturnSolutions;
    }

}
