//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.06 at 02:12:50 PM IST 
//


package com.jp.cleartrip.dto;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cleartrip.com/air/}index"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}segment-index"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}pricing-info-index"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}booking-class"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}cabin-type"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}ticket-type"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}booking-status" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}airline-pnr" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}ticket-number" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "index",
    "segmentIndex",
    "pricingInfoIndex",
    "bookingClass",
    "cabinType",
    "ticketType",
    "bookingStatus",
    "airlinePnr",
    "ticketNumber"
})
@XmlRootElement(name = "booking-info")
public class BookingInfo {

    @XmlElement(required = true)
    protected BigInteger index;
    @XmlElement(name = "segment-index", required = true)
    protected BigInteger segmentIndex;
    @XmlElement(name = "pricing-info-index", required = true)
    protected BigInteger pricingInfoIndex;
    @XmlElement(name = "booking-class", required = true)
    protected String bookingClass;
    @XmlElement(name = "cabin-type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cabinType;
    @XmlElement(name = "ticket-type", required = true)
    protected String ticketType;
    @XmlElement(name = "booking-status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bookingStatus;
    @XmlElement(name = "airline-pnr")
    protected String airlinePnr;
    @XmlElement(name = "ticket-number")
    protected String ticketNumber;

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

    /**
     * Gets the value of the segmentIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSegmentIndex() {
        return segmentIndex;
    }

    /**
     * Sets the value of the segmentIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSegmentIndex(BigInteger value) {
        this.segmentIndex = value;
    }

    /**
     * Gets the value of the pricingInfoIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPricingInfoIndex() {
        return pricingInfoIndex;
    }

    /**
     * Sets the value of the pricingInfoIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPricingInfoIndex(BigInteger value) {
        this.pricingInfoIndex = value;
    }

    /**
     * Gets the value of the bookingClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingClass() {
        return bookingClass;
    }

    /**
     * Sets the value of the bookingClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingClass(String value) {
        this.bookingClass = value;
    }

    /**
     * Gets the value of the cabinType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCabinType() {
        return cabinType;
    }

    /**
     * Sets the value of the cabinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCabinType(String value) {
        this.cabinType = value;
    }

    /**
     * Gets the value of the ticketType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketType() {
        return ticketType;
    }

    /**
     * Sets the value of the ticketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketType(String value) {
        this.ticketType = value;
    }

    /**
     * Gets the value of the bookingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingStatus() {
        return bookingStatus;
    }

    /**
     * Sets the value of the bookingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingStatus(String value) {
        this.bookingStatus = value;
    }

    /**
     * Gets the value of the airlinePnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirlinePnr() {
        return airlinePnr;
    }

    /**
     * Sets the value of the airlinePnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirlinePnr(String value) {
        this.airlinePnr = value;
    }

    /**
     * Gets the value of the ticketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketNumber() {
        return ticketNumber;
    }

    /**
     * Sets the value of the ticketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketNumber(String value) {
        this.ticketNumber = value;
    }

}
