//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.06 at 02:12:50 PM IST 
//


package com.jp.cleartrip.dto;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jp.cleartrip.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SegmentIndex_QNAME = new QName("http://www.cleartrip.com/air/", "segment-index");
    private final static QName _Amount_QNAME = new QName("http://www.cleartrip.com/air/", "amount");
    private final static QName _TicketNumber_QNAME = new QName("http://www.cleartrip.com/air/", "ticket-number");
    private final static QName _LastName_QNAME = new QName("http://www.cleartrip.com/air/", "last-name");
    private final static QName _Longitude_QNAME = new QName("http://www.cleartrip.com/air/", "longitude");
    private final static QName _IdNumber_QNAME = new QName("http://www.cleartrip.com/air/", "id-number");
    private final static QName _DateOfBirth_QNAME = new QName("http://www.cleartrip.com/air/", "date-of-birth");
    private final static QName _ArrivalDateTime_QNAME = new QName("http://www.cleartrip.com/air/", "arrival-date-time");
    private final static QName _Markup_QNAME = new QName("http://www.cleartrip.com/air/", "markup");
    private final static QName _PaxInfoIndex_QNAME = new QName("http://www.cleartrip.com/air/", "pax-info-index");
    private final static QName _BookingStatus_QNAME = new QName("http://www.cleartrip.com/air/", "booking-status");
    private final static QName _City_QNAME = new QName("http://www.cleartrip.com/air/", "city");
    private final static QName _Type_QNAME = new QName("http://www.cleartrip.com/air/", "type");
    private final static QName _Equipment_QNAME = new QName("http://www.cleartrip.com/air/", "equipment");
    private final static QName _FlightNumber_QNAME = new QName("http://www.cleartrip.com/air/", "flight-number");
    private final static QName _CardNumber_QNAME = new QName("http://www.cleartrip.com/air/", "card-number");
    private final static QName _Email_QNAME = new QName("http://www.cleartrip.com/air/", "email");
    private final static QName _CardType_QNAME = new QName("http://www.cleartrip.com/air/", "card-type");
    private final static QName _Category_QNAME = new QName("http://www.cleartrip.com/air/", "category");
    private final static QName _Mobile_QNAME = new QName("http://www.cleartrip.com/air/", "mobile");
    private final static QName _OperatingFlightNumber_QNAME = new QName("http://www.cleartrip.com/air/", "operating-flight-number");
    private final static QName _PassportNumber_QNAME = new QName("http://www.cleartrip.com/air/", "passport-number");
    private final static QName _LayoverDuration_QNAME = new QName("http://www.cleartrip.com/air/", "layover-duration");
    private final static QName _Latitude_QNAME = new QName("http://www.cleartrip.com/air/", "latitude");
    private final static QName _DepositAccountId_QNAME = new QName("http://www.cleartrip.com/air/", "deposit-account-id");
    private final static QName _Index_QNAME = new QName("http://www.cleartrip.com/air/", "index");
    private final static QName _FareBasisCode_QNAME = new QName("http://www.cleartrip.com/air/", "fare-basis-code");
    private final static QName _PinCode_QNAME = new QName("http://www.cleartrip.com/air/", "pin-code");
    private final static QName _Discount_QNAME = new QName("http://www.cleartrip.com/air/", "discount");
    private final static QName _Country_QNAME = new QName("http://www.cleartrip.com/air/", "country");
    private final static QName _Uri_QNAME = new QName("http://www.cleartrip.com/air/", "uri");
    private final static QName _Code_QNAME = new QName("http://www.cleartrip.com/air/", "code");
    private final static QName _TripId_QNAME = new QName("http://www.cleartrip.com/air/", "trip-id");
    private final static QName _CardHolderName_QNAME = new QName("http://www.cleartrip.com/air/", "card-holder-name");
    private final static QName _Name_QNAME = new QName("http://www.cleartrip.com/air/", "name");
    private final static QName _Title_QNAME = new QName("http://www.cleartrip.com/air/", "title");
    private final static QName _Landline_QNAME = new QName("http://www.cleartrip.com/air/", "landline");
    private final static QName _Stops_QNAME = new QName("http://www.cleartrip.com/air/", "stops");
    private final static QName _PricingInfoIndex_QNAME = new QName("http://www.cleartrip.com/air/", "pricing-info-index");
    private final static QName _CardCvv_QNAME = new QName("http://www.cleartrip.com/air/", "card-cvv");
    private final static QName _DepartureDateTime_QNAME = new QName("http://www.cleartrip.com/air/", "departure-date-time");
    private final static QName _OperatingAirline_QNAME = new QName("http://www.cleartrip.com/air/", "operating-airline");
    private final static QName _CardExpiryDate_QNAME = new QName("http://www.cleartrip.com/air/", "card-expiry-date");
    private final static QName _BaseFare_QNAME = new QName("http://www.cleartrip.com/air/", "base-fare");
    private final static QName _BookingClass_QNAME = new QName("http://www.cleartrip.com/air/", "booking-class");
    private final static QName _CityName_QNAME = new QName("http://www.cleartrip.com/air/", "city-name");
    private final static QName _PersonId_QNAME = new QName("http://www.cleartrip.com/air/", "person-id");
    private final static QName _PaymentType_QNAME = new QName("http://www.cleartrip.com/air/", "payment-type");
    private final static QName _CreatedAt_QNAME = new QName("http://www.cleartrip.com/air/", "created-at");
    private final static QName _Address_QNAME = new QName("http://www.cleartrip.com/air/", "address");
    private final static QName _IdType_QNAME = new QName("http://www.cleartrip.com/air/", "id-type");
    private final static QName _FirstName_QNAME = new QName("http://www.cleartrip.com/air/", "first-name");
    private final static QName _Duration_QNAME = new QName("http://www.cleartrip.com/air/", "duration");
    private final static QName _TotalFare_QNAME = new QName("http://www.cleartrip.com/air/", "total-fare");
    private final static QName _Taxes_QNAME = new QName("http://www.cleartrip.com/air/", "taxes");
    private final static QName _DepartureAirport_QNAME = new QName("http://www.cleartrip.com/air/", "departure-airport");
    private final static QName _PaymentStatus_QNAME = new QName("http://www.cleartrip.com/air/", "payment-status");
    private final static QName _StateName_QNAME = new QName("http://www.cleartrip.com/air/", "state-name");
    private final static QName _AirlinePnr_QNAME = new QName("http://www.cleartrip.com/air/", "airline-pnr");
    private final static QName _CountryName_QNAME = new QName("http://www.cleartrip.com/air/", "country-name");
    private final static QName _ArrivalAirport_QNAME = new QName("http://www.cleartrip.com/air/", "arrival-airport");
    private final static QName _FareKey_QNAME = new QName("http://www.cleartrip.com/air/", "fare-key");
    private final static QName _Fees_QNAME = new QName("http://www.cleartrip.com/air/", "fees");
    private final static QName _PaxType_QNAME = new QName("http://www.cleartrip.com/air/", "pax-type");
    private final static QName _LayoverAirport_QNAME = new QName("http://www.cleartrip.com/air/", "layover-airport");
    private final static QName _CabinType_QNAME = new QName("http://www.cleartrip.com/air/", "cabin-type");
    private final static QName _TicketType_QNAME = new QName("http://www.cleartrip.com/air/", "ticket-type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jp.cleartrip.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PricingElements }
     * 
     */
    public PricingElements createPricingElements() {
        return new PricingElements();
    }

    /**
     * Create an instance of {@link AncillaryData }
     * 
     */
    public AncillaryData createAncillaryData() {
        return new AncillaryData();
    }

    /**
     * Create an instance of {@link BookingInfoList }
     * 
     */
    public BookingInfoList createBookingInfoList() {
        return new BookingInfoList();
    }

    /**
     * Create an instance of {@link Segments }
     * 
     */
    public Segments createSegments() {
        return new Segments();
    }

    /**
     * Create an instance of {@link Flights }
     * 
     */
    public Flights createFlights() {
        return new Flights();
    }

    /**
     * Create an instance of {@link Solutions }
     * 
     */
    public Solutions createSolutions() {
        return new Solutions();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link ContactDetail }
     * 
     */
    public ContactDetail createContactDetail() {
        return new ContactDetail();
    }

    /**
     * Create an instance of {@link PaxPricingInfo }
     * 
     */
    public PaxPricingInfo createPaxPricingInfo() {
        return new PaxPricingInfo();
    }

    /**
     * Create an instance of {@link AirSearchResult }
     * 
     */
    public AirSearchResult createAirSearchResult() {
        return new AirSearchResult();
    }

    /**
     * Create an instance of {@link PaxInfoList }
     * 
     */
    public PaxInfoList createPaxInfoList() {
        return new PaxInfoList();
    }

    /**
     * Create an instance of {@link StopDetails }
     * 
     */
    public StopDetails createStopDetails() {
        return new StopDetails();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link PaxPricingInfoList }
     * 
     */
    public PaxPricingInfoList createPaxPricingInfoList() {
        return new PaxPricingInfoList();
    }

    /**
     * Create an instance of {@link PricingInfoList }
     * 
     */
    public PricingInfoList createPricingInfoList() {
        return new PricingInfoList();
    }

    /**
     * Create an instance of {@link PricingInfo }
     * 
     */
    public PricingInfo createPricingInfo() {
        return new PricingInfo();
    }

    /**
     * Create an instance of {@link PricingSummary }
     * 
     */
    public PricingSummary createPricingSummary() {
        return new PricingSummary();
    }

    /**
     * Create an instance of {@link StopsDetails }
     * 
     */
    public StopsDetails createStopsDetails() {
        return new StopsDetails();
    }

    /**
     * Create an instance of {@link OnwardSolutions }
     * 
     */
    public OnwardSolutions createOnwardSolutions() {
        return new OnwardSolutions();
    }

    /**
     * Create an instance of {@link Solution }
     * 
     */
    public Solution createSolution() {
        return new Solution();
    }

    /**
     * Create an instance of {@link Flight }
     * 
     */
    public Flight createFlight() {
        return new Flight();
    }

    /**
     * Create an instance of {@link CardDetail }
     * 
     */
    public CardDetail createCardDetail() {
        return new CardDetail();
    }

    /**
     * Create an instance of {@link PaxInfo }
     * 
     */
    public PaxInfo createPaxInfo() {
        return new PaxInfo();
    }

    /**
     * Create an instance of {@link ReturnSolutions }
     * 
     */
    public ReturnSolutions createReturnSolutions() {
        return new ReturnSolutions();
    }

    /**
     * Create an instance of {@link Airlines }
     * 
     */
    public Airlines createAirlines() {
        return new Airlines();
    }

    /**
     * Create an instance of {@link BookingInfo }
     * 
     */
    public BookingInfo createBookingInfo() {
        return new BookingInfo();
    }

    /**
     * Create an instance of {@link Airlines.Airline }
     * 
     */
    public Airlines.Airline createAirlinesAirline() {
        return new Airlines.Airline();
    }

    /**
     * Create an instance of {@link Airports }
     * 
     */
    public Airports createAirports() {
        return new Airports();
    }

    /**
     * Create an instance of {@link PricingElement }
     * 
     */
    public PricingElement createPricingElement() {
        return new PricingElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "segment-index")
    public JAXBElement<BigInteger> createSegmentIndex(BigInteger value) {
        return new JAXBElement<BigInteger>(_SegmentIndex_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "amount")
    public JAXBElement<Double> createAmount(Double value) {
        return new JAXBElement<Double>(_Amount_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "ticket-number")
    public JAXBElement<String> createTicketNumber(String value) {
        return new JAXBElement<String>(_TicketNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "last-name")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "longitude")
    public JAXBElement<String> createLongitude(String value) {
        return new JAXBElement<String>(_Longitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "id-number")
    public JAXBElement<String> createIdNumber(String value) {
        return new JAXBElement<String>(_IdNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "date-of-birth")
    public JAXBElement<String> createDateOfBirth(String value) {
        return new JAXBElement<String>(_DateOfBirth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "arrival-date-time")
    public JAXBElement<XMLGregorianCalendar> createArrivalDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ArrivalDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "markup")
    public JAXBElement<Float> createMarkup(Float value) {
        return new JAXBElement<Float>(_Markup_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "pax-info-index")
    public JAXBElement<BigInteger> createPaxInfoIndex(BigInteger value) {
        return new JAXBElement<BigInteger>(_PaxInfoIndex_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "booking-status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBookingStatus(String value) {
        return new JAXBElement<String>(_BookingStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "city")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaxTypeEnumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "type")
    public JAXBElement<PaxTypeEnumType> createType(PaxTypeEnumType value) {
        return new JAXBElement<PaxTypeEnumType>(_Type_QNAME, PaxTypeEnumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "equipment")
    public JAXBElement<String> createEquipment(String value) {
        return new JAXBElement<String>(_Equipment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "flight-number")
    public JAXBElement<String> createFlightNumber(String value) {
        return new JAXBElement<String>(_FlightNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "card-number")
    public JAXBElement<BigInteger> createCardNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_CardNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "card-type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCardType(String value) {
        return new JAXBElement<String>(_CardType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "category")
    public JAXBElement<String> createCategory(String value) {
        return new JAXBElement<String>(_Category_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "mobile")
    public JAXBElement<String> createMobile(String value) {
        return new JAXBElement<String>(_Mobile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "operating-flight-number")
    public JAXBElement<String> createOperatingFlightNumber(String value) {
        return new JAXBElement<String>(_OperatingFlightNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "passport-number")
    public JAXBElement<String> createPassportNumber(String value) {
        return new JAXBElement<String>(_PassportNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "layover-duration")
    public JAXBElement<BigInteger> createLayoverDuration(BigInteger value) {
        return new JAXBElement<BigInteger>(_LayoverDuration_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "latitude")
    public JAXBElement<String> createLatitude(String value) {
        return new JAXBElement<String>(_Latitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "deposit-account-id")
    public JAXBElement<String> createDepositAccountId(String value) {
        return new JAXBElement<String>(_DepositAccountId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "index")
    public JAXBElement<BigInteger> createIndex(BigInteger value) {
        return new JAXBElement<BigInteger>(_Index_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "fare-basis-code")
    public JAXBElement<String> createFareBasisCode(String value) {
        return new JAXBElement<String>(_FareBasisCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "pin-code")
    public JAXBElement<String> createPinCode(String value) {
        return new JAXBElement<String>(_PinCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "discount")
    public JAXBElement<Float> createDiscount(Float value) {
        return new JAXBElement<Float>(_Discount_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "uri")
    public JAXBElement<String> createUri(String value) {
        return new JAXBElement<String>(_Uri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "code")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "trip-id")
    public JAXBElement<String> createTripId(String value) {
        return new JAXBElement<String>(_TripId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "card-holder-name")
    public JAXBElement<String> createCardHolderName(String value) {
        return new JAXBElement<String>(_CardHolderName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "title")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "landline")
    public JAXBElement<String> createLandline(String value) {
        return new JAXBElement<String>(_Landline_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "stops")
    public JAXBElement<BigInteger> createStops(BigInteger value) {
        return new JAXBElement<BigInteger>(_Stops_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "pricing-info-index")
    public JAXBElement<BigInteger> createPricingInfoIndex(BigInteger value) {
        return new JAXBElement<BigInteger>(_PricingInfoIndex_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "card-cvv")
    public JAXBElement<String> createCardCvv(String value) {
        return new JAXBElement<String>(_CardCvv_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "departure-date-time")
    public JAXBElement<XMLGregorianCalendar> createDepartureDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DepartureDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "operating-airline")
    public JAXBElement<String> createOperatingAirline(String value) {
        return new JAXBElement<String>(_OperatingAirline_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "card-expiry-date")
    public JAXBElement<String> createCardExpiryDate(String value) {
        return new JAXBElement<String>(_CardExpiryDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "base-fare")
    public JAXBElement<Float> createBaseFare(Float value) {
        return new JAXBElement<Float>(_BaseFare_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "booking-class")
    public JAXBElement<String> createBookingClass(String value) {
        return new JAXBElement<String>(_BookingClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "city-name")
    public JAXBElement<String> createCityName(String value) {
        return new JAXBElement<String>(_CityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "person-id")
    public JAXBElement<String> createPersonId(String value) {
        return new JAXBElement<String>(_PersonId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "payment-type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPaymentType(String value) {
        return new JAXBElement<String>(_PaymentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "created-at")
    public JAXBElement<String> createCreatedAt(String value) {
        return new JAXBElement<String>(_CreatedAt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "id-type")
    public JAXBElement<IDType> createIdType(IDType value) {
        return new JAXBElement<IDType>(_IdType_QNAME, IDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "first-name")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "duration")
    public JAXBElement<BigInteger> createDuration(BigInteger value) {
        return new JAXBElement<BigInteger>(_Duration_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "total-fare")
    public JAXBElement<Float> createTotalFare(Float value) {
        return new JAXBElement<Float>(_TotalFare_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "taxes")
    public JAXBElement<Float> createTaxes(Float value) {
        return new JAXBElement<Float>(_Taxes_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "departure-airport")
    public JAXBElement<String> createDepartureAirport(String value) {
        return new JAXBElement<String>(_DepartureAirport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "payment-status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPaymentStatus(String value) {
        return new JAXBElement<String>(_PaymentStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "state-name")
    public JAXBElement<String> createStateName(String value) {
        return new JAXBElement<String>(_StateName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "airline-pnr")
    public JAXBElement<String> createAirlinePnr(String value) {
        return new JAXBElement<String>(_AirlinePnr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "country-name")
    public JAXBElement<String> createCountryName(String value) {
        return new JAXBElement<String>(_CountryName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "arrival-airport")
    public JAXBElement<String> createArrivalAirport(String value) {
        return new JAXBElement<String>(_ArrivalAirport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "fare-key")
    public JAXBElement<String> createFareKey(String value) {
        return new JAXBElement<String>(_FareKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "fees")
    public JAXBElement<Float> createFees(Float value) {
        return new JAXBElement<Float>(_Fees_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaxTypeEnumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "pax-type")
    public JAXBElement<PaxTypeEnumType> createPaxType(PaxTypeEnumType value) {
        return new JAXBElement<PaxTypeEnumType>(_PaxType_QNAME, PaxTypeEnumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "layover-airport")
    public JAXBElement<String> createLayoverAirport(String value) {
        return new JAXBElement<String>(_LayoverAirport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "cabin-type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCabinType(String value) {
        return new JAXBElement<String>(_CabinType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cleartrip.com/air/", name = "ticket-type")
    public JAXBElement<String> createTicketType(String value) {
        return new JAXBElement<String>(_TicketType_QNAME, String.class, null, value);
    }

}
