//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.06 at 02:12:50 PM IST 
//


package com.jp.cleartrip.dto;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.cleartrip.com/air/}pax-info-index"/>
 *           &lt;element ref="{http://www.cleartrip.com/air/}pax-type"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.cleartrip.com/air/}pricing-info-list"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}booking-info-list"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paxInfoIndex",
    "paxType",
    "pricingInfoList",
    "bookingInfoList"
})
@XmlRootElement(name = "pax-pricing-info")
public class PaxPricingInfo {

    @XmlElement(name = "pax-info-index")
    protected BigInteger paxInfoIndex;
    @XmlElement(name = "pax-type")
    protected PaxTypeEnumType paxType;
    @XmlElement(name = "pricing-info-list", required = true)
    protected PricingInfoList pricingInfoList;
    @XmlElement(name = "booking-info-list", required = true)
    protected BookingInfoList bookingInfoList;

    /**
     * Gets the value of the paxInfoIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaxInfoIndex() {
        return paxInfoIndex;
    }

    /**
     * Sets the value of the paxInfoIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaxInfoIndex(BigInteger value) {
        this.paxInfoIndex = value;
    }

    /**
     * Gets the value of the paxType property.
     * 
     * @return
     *     possible object is
     *     {@link PaxTypeEnumType }
     *     
     */
    public PaxTypeEnumType getPaxType() {
        return paxType;
    }

    /**
     * Sets the value of the paxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaxTypeEnumType }
     *     
     */
    public void setPaxType(PaxTypeEnumType value) {
        this.paxType = value;
    }

    /**
     * Gets the value of the pricingInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link PricingInfoList }
     *     
     */
    public PricingInfoList getPricingInfoList() {
        return pricingInfoList;
    }

    /**
     * Sets the value of the pricingInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingInfoList }
     *     
     */
    public void setPricingInfoList(PricingInfoList value) {
        this.pricingInfoList = value;
    }

    /**
     * Gets the value of the bookingInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link BookingInfoList }
     *     
     */
    public BookingInfoList getBookingInfoList() {
        return bookingInfoList;
    }

    /**
     * Sets the value of the bookingInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingInfoList }
     *     
     */
    public void setBookingInfoList(BookingInfoList value) {
        this.bookingInfoList = value;
    }

}
