//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.06 at 02:12:50 PM IST 
//


package com.jp.cleartrip.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.cleartrip.com/air/}base-fare"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}markup" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}discount" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}fees" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}taxes"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}total-fare"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "pricing-summary")
public class PricingSummary {

    @XmlElement(name = "base-fare")
    protected float baseFare;
    protected Float markup;
    protected Float discount;
    protected Float fees;
    protected float taxes;
    @XmlElement(name = "total-fare")
    protected float totalFare;

    /**
     * Gets the value of the baseFare property.
     * 
     */
    public float getBaseFare() {
        return baseFare;
    }

    /**
     * Sets the value of the baseFare property.
     * 
     */
    public void setBaseFare(float value) {
        this.baseFare = value;
    }

    /**
     * Gets the value of the markup property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMarkup() {
        return markup;
    }

    /**
     * Sets the value of the markup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMarkup(Float value) {
        this.markup = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDiscount(Float value) {
        this.discount = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFees(Float value) {
        this.fees = value;
    }

    /**
     * Gets the value of the taxes property.
     * 
     */
    public float getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     * 
     */
    public void setTaxes(float value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the totalFare property.
     * 
     */
    public float getTotalFare() {
        return totalFare;
    }

    /**
     * Sets the value of the totalFare property.
     * 
     */
    public void setTotalFare(float value) {
        this.totalFare = value;
    }

}
