//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.06 at 02:12:50 PM IST 
//


package com.jp.cleartrip.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cleartrip.com/air/}pricing-summary"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}flights"/>
 *         &lt;element ref="{http://www.cleartrip.com/air/}pax-pricing-info-list"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pricingSummary",
    "flights",
    "paxPricingInfoList"
})
@XmlRootElement(name = "solution")
public class Solution {

    @XmlElement(name = "pricing-summary", required = true)
    protected PricingSummary pricingSummary;
    @XmlElement(required = true)
    protected Flights flights;
    @XmlElement(name = "pax-pricing-info-list", required = true)
    protected PaxPricingInfoList paxPricingInfoList;

    /**
     * Gets the value of the pricingSummary property.
     * 
     * @return
     *     possible object is
     *     {@link PricingSummary }
     *     
     */
    public PricingSummary getPricingSummary() {
        return pricingSummary;
    }

    /**
     * Sets the value of the pricingSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingSummary }
     *     
     */
    public void setPricingSummary(PricingSummary value) {
        this.pricingSummary = value;
    }

    /**
     * Gets the value of the flights property.
     * 
     * @return
     *     possible object is
     *     {@link Flights }
     *     
     */
    public Flights getFlights() {
        return flights;
    }

    /**
     * Sets the value of the flights property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flights }
     *     
     */
    public void setFlights(Flights value) {
        this.flights = value;
    }

    /**
     * Gets the value of the paxPricingInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link PaxPricingInfoList }
     *     
     */
    public PaxPricingInfoList getPaxPricingInfoList() {
        return paxPricingInfoList;
    }

    /**
     * Sets the value of the paxPricingInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaxPricingInfoList }
     *     
     */
    public void setPaxPricingInfoList(PaxPricingInfoList value) {
        this.paxPricingInfoList = value;
    }

}
