INSERT INTO IECP_APP.PERSISTENCE_USERS(ID_PREF,USER_ID,USER_NAME)VALUES(1,10,'Dimit')
INSERT INTO IECP_APP.PERSISTENCE_USERS(ID_PREF,USER_ID,USER_NAME)VALUES(2,11,'Chadha')


INSERT INTO IECP_APP.USER_ACCOUNTS_PERSIST(ID_PREF,ID,SORT_CODE,PRODUCT_NUMBER) VALUES(1,1,'201201','123456')
INSERT INTO IECP_APP.USER_ACCOUNTS_PERSIST(ID_PREF,ID,SORT_CODE,PRODUCT_NUMBER) VALUES(1,2,'201301','123457')
INSERT INTO IECP_APP.USER_ACCOUNTS_PERSIST(ID_PREF,ID,SORT_CODE,PRODUCT_NUMBER) VALUES(1,3,'201401','123458')
INSERT INTO IECP_APP.USER_ACCOUNTS_PERSIST(ID_PREF,ID,SORT_CODE,PRODUCT_NUMBER) VALUES(2,4,'101401','444444')




#Hibernate: 
select this_.ID_PREF as ID1_4_0_, this_.user_Id as user2_4_0_, this_.user_Name as user3_4_0_ from IECP_APP.Persistence_Users this_ where this_.user_Id=10
select accountspe0_.ID_PREF as ID1_1_, 
accountspe0_.ID_PREF as ID1_3_0_, 
accountspe0_.SORT_CODE as SORT2_3_0_, 
accountspe0_.PRODUCT_NUMBER as PRODUCT3_3_0_ from IECP_APP.User_Accounts_Persist accountspe0_ where accountspe0_.ID_PREF=10



